name: Build and Push to ghcr.io

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the image'
        required: true
        default: 'latest'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push API Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/wasinuddy/ayanami-fan-controller:${{ github.event.inputs.tag }}
            ghcr.io/wasinuddy/ayanami-fan-controller:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max